services:
  
  manager:
    image: docker:dind
    privileged: true
    container_name: manager
    networks:
      - swarm_net
    ports:
      - 9080:8080
      - 9081:8082
      - 3308:3307
      - 9091:5001
    volumes:
      - manager_data:/var/lib/docker
      - manager_stacks_data:/home/devops/stacks
  worker1:
    image: docker:dind
    privileged: true
    container_name: worker1
    networks:
      - swarm_net
    ports:
      - 9092:5001
    volumes:
      - worker1_data:/var/lib/docker
  worker2:
    image: docker:dind
    privileged: true
    container_name: worker2
    networks:
      - swarm_net
    ports:
      - 9093:5001
    volumes:
      - worker2_data:/var/lib/docker

networks:
  swarm_net:

volumes:
  manager_data:
  worker1_data:
  worker2_data:
  manager_stacks_data: