services:
  compose_mysql:
    image: fercdevv/mysql-project-paths:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE_PATH: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD_FILE_PATH: /run/secrets/MYSQL_PASSWORD
    volumes:
      - compose-mysql-data:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    networks:
      - compose_network
    ports:
      - 3307:3306
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:         # Tope maximo de consumo
          cpus: "0.5" # representa el 50% de un CPU [0.25 => 1/4 de un CPU, 25% de un CPU] (Core)
          memory: 512M # representa 512 Megabytes de RAM / Se puede utilizar tambien MB/ tambien podemos tener GB o G (Gigabytes) de RAM
        reservations:   # Lo minimo garantizado de consumo
          cpus: "0.25"
          memory: 256M
      labels:
        app: web_project
        service: compose_mysql
        environment: test
        team: devops
        version: "1.0"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  backend:
    image: fercdevv/backend-project:latest
    depends_on:
      - compose_mysql
    environment:
      DB_HOST: compose_mysql
      DB_NAME: demo_db
      DB_USER: demo_user
      DB_PASS: demo_pass
      DB_PORT: 3306
    networks:
      - compose_network
    ports:
      - 5001:4000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure   # recomendaciones (none -> default | on-failure | any)
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      labels:
        app: web_project
        service: backend
        environment: test
        team: devops
        version: "1.0"
networks:
  compose_network:
    driver: overlay

volumes:
  compose-mysql-data:

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true